alcott = Author.create(name: "Louisa May Alcott")
atwood = Author.create(name: "Margaret Atwood")
austen = Author.create(name: "Jane Austen")
barrie = Author.create(name: "J.M. Barrie")
blume = Author.create(name: "Judy Blume")
bradbury = Author.create(name: "Ray Bradbury")
brontechar = Author.create(name: "Charlotte Bronte")
bronteem = Author.create(name: "Wuthering Heights")
crichton = Author.create(name: "Michael Crichton")
dickens = Author.create(name: "Charles Dickens")
flynn = Author.create(name: "Gillian Flynn")
gaiman = Author.create(name: "Neil Gaiman")
grisham = Author.create(name: "John Grisham")
king = Author.create(name: "Stephen King")
kwan = Author.create(name: "Kevin Kwan")
picoult = Author.create(name: "Jodi Picoult")
rice = Author.create(name: "Anne Rice")
rowling = Author.create(name: "J.K. Rowling")
rule = Author.create(name: "Ann Rule")
shelley = Author.create(name: "Mary Wollstonecraft Shelley")
stevenson = Author.create(name: "Robert Louis Stevenson")
stoker = Author.create(name: "Bram Stoker")
tan = Author.create(name: "Amy Tan")
thomas = Author.create(name: "Angie Thomas")
weir = Author.create(name: "Andy Weir")


stardust = Book.create(title: "Stardust", author_id: 12, cover: "https://i.pinimg.com/originals/18/04/7a/18047a8eb286f0340fc21dfbe65bf2fb.jpg")
americangod = Book.create(title: "American Gods", author_id: 12, cover: "https://images-na.ssl-images-amazon.com/images/I/51Pb-OAREFL._SX327_BO1,204,203,200_.jpg")
handmaid = Book.create(title: "The Handmaid's Tale", author_id: 2, cover: "https://images-na.ssl-images-amazon.com/images/I/91Idmo2GtiL.jpg")
jurassic = Book.create(title: "Jurassic Park", author_id: 9, cover: "http://www.michaelcrichton.com/wp-content/uploads/2014/12/book-jurassicpark.jpg")
pan = Book.create(title: "Peter Pan", author_id: 4, cover: "https://static.greatbigcanvas.com/images/singlecanvas_thick_none/corbis/cover-of-peter-pan-and-wendy-by-j-m-barrie,2233356.jpg?max=1000")
vampireinterview = Book.create(title: "Interview with the Vampire", author_id: 17, cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1380631642i/43763.jpg")
joy = Book.create(title: "The Joy Luck Club", author_id: 23, cover: "https://i0.wp.com/www.nationalbook.org/wp-content/uploads/2015/12/1989_The-Joy-Luck-Club-by-Amy-Tan.jpg?fit=280%2C420&ssl=1")
stranger = Book.create(title: "The Stranger Beside Me", author_id: 19, cover: "https://images-na.ssl-images-amazon.com/images/I/51CgK5tPG2L._SX308_BO1,204,203,200_.jpg")
lestat = Book.create(title: "The Vampire Lestat", author_id: 17, cover: "https://vignette.wikia.nocookie.net/vampirechroncles/images/a/a1/The_Vampire_Lestat_book_cover.jpg/revision/latest?cb=20160528183024")
killtime = Book.create(title: "A Time to Kill", author_id: 13, cover: "https://images.penguinrandomhouse.com/cover/9780385338608")
firm = Book.create(title: "The Firm", author_id: 13, cover: "https://upload.wikimedia.org/wikipedia/en/8/80/The_Firm_Grisham.jpg")
client = Book.create(title: "The Client", author_id: 13, cover: "https://images-na.ssl-images-amazon.com/images/I/51Zr54Y%2BugL._SX277_BO1,204,203,200_.jpg")
shining = Book.create(title: "The Shining", author_id: 14, cover: "https://images.penguinrandomhouse.com/cover/9780385121675")
it = Book.create(title: "It", author_id: 14, cover: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781501182099/it-9781501182099_hr.jpg")
carrie = Book.create(title: "Carrie", author_id: 14, cover: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1166254258i/10592._SY475_.jpg")
sematary = Book.create(title: "Pet Sematary", author_id: 14, cover: "https://i0.wp.com/www.tor.com/wp-content/uploads/2014/12/PetSematary12.jpg?resize=250%2C405&type=vertical")
cujo = Book.create(title: "Cujo", author_id: 14, cover: "https://d3myrwj42s63no.cloudfront.net/300/045/116/135/1/0451161351.jpg")
dome = Book.create(title: "Under the Dome", author_id: 14, cover: "https://vignette.wikia.nocookie.net/underthedome/images/c/cc/Bookcover_-_part1.jpg/revision/latest?cb=20140904212007")
greenmile = Book.create(title: "The Green Mile", author_id: 14, cover: "https://prodimage.images-bn.com/pimages/9781501192265_p0_v2_s550x406.jpg")
christine = Book.create(title: "Christine", author_id: 14, cover: "https://i1.wp.com/www.tor.com/wp-content/uploads/2014/12/Christine6.jpg?fit=250%2C+9999&crop=0%2C0%2C100%2C418px&ssl=1&w=240")
rutheregod = Book.create(title: "Are You There God? It's Me, Margaret", author_id: 5, cover: "https://covers.openlibrary.org/b/id/6943479-M.jpg")
freckle = Book.create(title: "Freckle Juice", author_id: 5, cover: "https://panmacmillanapi.blob.core.windows.net/pmapi/e12a8195-4610-4b2d-fa9f-08d58e45775c/editions/a1f1369e-e574-40d6-f00b-08d5dcd8c2c8/original_400_600.jpg")
deenie = Book.create(title: "Deenie", author_id: 5, cover: "https://www.scholastic.com/content5/media/products/98/9780440932598_mres.jpg")
greatsheila = Book.create(title: "Otherwise Known as Sheila the Great", author_id: 5, cover: "https://www.scholastic.com/content5/media/products/74/9780439559874_mres.jpg")
coraline = Book.create(title: "Coraline", author_id: 12, cover: "https://media.bloomsbury.com/rep/bj/9781408841754.jpg")
oceanlane = Book.create(title: "The Ocean at the End of the Lane", author_id: 12, cover: "http://www.mariannedepierres.com/wp-content/uploads/2014/08/gAIMAN_The-Ocean-at-the-End-of-the-Lane-Cover.jpg")
graveyard = Book.create(title: "The Graveyard Book", author_id: 12, cover: "https://i.harperapps.com/covers/9780062349187/x510.jpg")
neverwhere = Book.create(title: "Neverwhere", author_id: 12, cover: "https://i.harperapps.com/covers/9780062821331/x510.jpg")
anansi = Book.create(title: "Anansi Boys", author_id: 12, cover: "https://www.jwkbooks.com/pictures/medium/21230.jpg")
littlewomen = Book.create(title: "Little Women", author_id: 1, cover: "https://images.penguinrandomhouse.com/cover/9781524704735")
joboys = Book.create(title: "Jo's Boys", author_id: 1, cover: "http://www.setonbooks.com/sempics/M-HSEN-2118946.jpg")
littlemen = Book.create(title: "Little Men", author_id: 1, cover: "https://louisamayalcottismypassion.files.wordpress.com/2014/02/cover.jpg")
pride = Book.create(title: "Pride and Prejudice", author_id: 3, cover: "https://cdn.shopify.com/s/files/1/0953/9884/products/Pride-And-Prejudice-Book-Cover-Locket-Necklace-keyring-silver-Bronze-tone-B0964.jpg?v=1558470191")
sense = Book.create(title: "Sense and Sensibility", author_id: 3, cover: "https://images.penguinrandomhouse.com/cover/9780375756733")
persuasion = Book.create(title: "Persuasion", author_id: 3, cover: "https://images.penguinrandomhouse.com/cover/9780307386854")
mansfield = Book.create(title: "Mansfield Park", author_id: 3, cover: "https://images.penguinrandomhouse.com/cover/9780307386885")
emma = Book.create(title: "Emma", author_id: 3, cover: "https://images.penguinrandomhouse.com/cover/9780553212730")
northanger = Book.create(title: "Northanger Abbey", author_id: 3, cover: "https://images.penguinrandomhouse.com/cover/9780553211979")
eyre = Book.create(title: "Jane Eyre", author_id: 7, cover: "https://images.penguinrandomhouse.com/cover/9780307455192")
wuthering = Book.create(title: "Wuthering Heights", author_id: 8, cover: "https://images.penguinrandomhouse.com/cover/9780553212587")
dracula = Book.create(title: "Dracula", author_id: 22, cover: "https://kbimages1-a.akamaihd.net/b9bb2f61-d2dc-4647-b368-50126e8e6e89/353/569/90/False/dracula-585.jpg")
frankenstein = Book.create(title: "Frankenstein", author_id: 20, cover: "https://images.penguinrandomhouse.com/cover/9780553212471")
jekyll = Book.create(title: "The Strange Case of Dr. Jekyll and Mr. Hyde", author: stevenson, cover: "https://cdn.waterstones.com/bookjackets/large/9780/1983/9780198329909.jpg")
treasure = Book.create(title: "Treasure Island", author_id: 21, cover: "https://d28hgpri8am2if.cloudfront.net/book_images/cvr9781416500292_9781416500292_lg.jpg")
hp1 = Book.create(title: "Harry Potter and the Sorcerer's Stone", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/51HSkTKlauL._SX346_BO1,204,203,200_.jpg")
hp2 = Book.create(title: "Harry Potter and the Chamber of Secrets", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/51jNORv6nQL._SX340_BO1,204,203,200_.jpg")
hp3 = Book.create(title: "Harry Potter and the Prisoner of Azkaban", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/81lAPl9Fl0L.jpg")
hp4 = Book.create(title: "Harry Potter and the Goblet of Fire", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/61wuP9E162L._SY606_.jpg")
hp5 = Book.create(title: "Harry Potter and the Order of the Phoenix", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/91TpLHDnuFL.jpg")
hp6 = Book.create(title: "Harry Potter and the Half-Blood Prince", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/51uO1pQc5oL._SX329_BO1,204,203,200_.jpg")
hp7 = Book.create(title: "Harry Potter and the Deathly Hallows", author_id: 18, cover: "https://images-na.ssl-images-amazon.com/images/I/71Q1Iu4suSL._SY606_.jpg")
twocity = Book.create(title: "A Tale of Two Cities", author_id: 10, cover: "https://images.penguinrandomhouse.com/cover/9780451530578")
christmascarol = Book.create(title: "A Christmas Carol", author_id: 10, cover: "https://images-na.ssl-images-amazon.com/images/I/51%2BGDJ0svfL._SX359_BO1,204,203,200_.jpg")
richasian = Book.create(title: "Crazy Rich Asians", author_id: 15, cover: "https://images-na.ssl-images-amazon.com/images/I/7144OITcNML.jpg")
richasian2 = Book.create(title: "China Rich Girlfriend", author_id: 15, cover: "https://images.penguinrandomhouse.com/cover/9780385539098")
richasian3 = Book.create(title: "Rich People Problems", author_id: 15, cover: "https://images.penguinrandomhouse.com/cover/9780385542241")
hate = Book.create(title: "The Hate U Give", author_id: 24, cover: "https://www.booktopia.com.au/http_coversbooktopiacomau/big/9781406372151/0000/the-hate-u-give.jpg")
lightspark = Book.create(title: "A Spark of Light", author_id: 16, cover: "https://images-na.ssl-images-amazon.com/images/I/81-nRPsTSjL.jpg")
martian = Book.create(title: "The Martian", author_id: 25, cover: "https://images-na.ssl-images-amazon.com/images/I/81wFMY9OAFL.jpg")
gone = Book.create(title: "Gone Girl", author_id: 11, cover: "https://images-na.ssl-images-amazon.com/images/I/516Gb2s1eGL._SX324_BO1,204,203,200_.jpg")
marschron = Book.create(title: "The Martian Chronicles", author_id: 6, cover: "https://images-na.ssl-images-amazon.com/images/I/518WxaFw0rL._SX307_BO1,204,203,200_.jpg")
illustrated = Book.create(title: "The Illustrated Man", author_id: 6, cover: "https://images-na.ssl-images-amazon.com/images/I/51fRL1sEdJL.jpg")
faren = Book.create(title: "Farenheit 451", author_id: 6, cover: "https://images-na.ssl-images-amazon.com/images/I/71OFqSRFDgL.jpg")
rocket = Book.create(title: "R is for Rocket", author_id: 6, cover: "https://images-na.ssl-images-amazon.com/images/I/51qsct9meYL._SX308_BO1,204,203,200_.jpg")
